title: "데일리 스코프"
description: "요즘 화제가 되는 이야기들을 짧게 정리해서 전합니다"
url: "https://miyaumiyau.github.io"
baseurl: "/T419_Blog"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

show_excerpts: true

# 상단 메뉴에 표시할 페이지
header_pages:
  - categories.md
